apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: log-agent
  namespace: cka
  labels:
    app: logs
spec:
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      containers:
      - name: log-agent
        image: busybox:1.36
        command: ["sh", "-c", "ls -lah /var/log && sleep infinity"]
        volumeMounts:
        - name: varlog
          mountPath: /var/log
          readOnly: true
      volumes:
      - name: varlog
        hostPath:
          path: /var/log
          type: Directory

  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1



